config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :photos, only: :index do
    collection do
      get 'search'
    end
  end

  root 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flickr.rb
class Flickr
  attr_accessor :error, :uri

	def search( free_text )
    # Refer https://www.flickr.com/services/api/flickr.photos.search.html for uri generation
    @uri = URI(URI.encode("https://api.flickr.com/services/rest/?api_key=#{FLICKR_API_KEY}&method=flickr.photos.search&text=#{free_text}"))

    if response_hash
      if response_hash['rsp']['stat'] == 'ok'
        if response_hash['rsp']['photos']['photo']
          return response_hash['rsp']['photos']['photo'].map{ |photo| Photo.new(photo) }
        else
          self.error = "There are no photos that match your search"
        end
      elsif response_hash['rsp']['stat'] == 'fail'
        self.error = response_hash['rsp']['err']['msg']
      end
    else
      self.error = "Something went wrong, please try again"
    end
    []
  end

  def response_hash
    Hash.from_xml( Net::HTTP.get(uri) )
  end
end

app/models/photo.rb
class Photo
  attr_reader :id, :secret, :server, :farm

  def initialize( attributes = {} )
    @id      = attributes['id']
    @secret  = attributes['secret']
    @server  = attributes['server']
    @farm    = attributes['farm']
  end


  # Refer https://www.flickr.com/services/api/misc.urls.html for url generation

  def url_small
    "https://farm#{farm}.staticflickr.com/#{server}/#{id}_#{secret}_q.jpg"
  end

  def url_large
    "https://farm#{farm}.staticflickr.com/#{server}/#{id}_#{secret}_c.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index

  end

  def search
    if session[:searched].blank? || session[:searched][:search] != params[:search]
      flickr = Flickr.new
      session[:searched] = { search: params[:search], photos: flickr.search(params[:search]) }
    end

    @photos = session[:searched][:photos].paginate(page: params[:page], per_page: 12)

    flash.now[:error] = flickr.error if flickr && flickr.error

    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FlickrPhotoSearch" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav affix">
            <p> Search Flickr for photos </p>
            <%= form_tag search_photos_path, method: :get do %>
              <%= text_field_tag :search %>
              <%= submit_tag "Search", class: "submit" %>
            <% end %>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>

app/views/photos/_photo_modal.html.erb
<div class="modal fade" id="photo-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
     <%= image_tag "" %>
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/photos/index.html.erb
<% unless @photos.blank? %>
  <%= will_paginate %>
  <ul class="thumbnails">
    <% @photos.each do |photo| %>
      <li class="span3">
        <%= link_to image_tag( photo.url_small ), '#', class: "thumbnail", data: { imgpath: photo.url_large } %>
      </li>
    <% end %>
  </ul>
  <%= will_paginate %>
<% end %>

<%= render 'photo_modal' %>